mondoohq/actions

action.yaml
=> Action name can't match an existing user

action.yaml
This way our assets show up as CI/CD
=> Detect CI/CD during the scan

README.md, action.yaml
This PR adds new `output_format` and `score_threshold` inputs. Default values have been configured with `v6` defaults.
Signed-off-by: Scott Ford <scott@scottford.io>
=> Adds output_format and score_threshold inputs

README.md, action.yaml
This could be useful in some cases. My use-case is enabling verbose output to debug issues
=> ⭐ Allow specifying extra command-line arguments

README.md, action.yaml
Three changes:
- Fix script to execute for `terraform` instead of `tf`
- Fix README to reference `terraform`
- Add Terraform example.
=> Fix tf to terraform as tf doesn't work

action.yaml
=> Use Mondoo Client naming throughout

action.yaml
This will fix failures in the action
This reverts commit 8e17b9d29f6d330584d70cd53f2818a44175194f.
=> Revert "get rid of --path for terraform, as path is always required and not an optional (#12)"

.github/test_files/Dockerfile, .github/test_files/k8s-manifest.yaml, .github/test_files/tf/deployment.tf, .github/test_files/tf/main.tf, .github/test_files/tf/outputs.tf, .github/test_files/tf/provider.tf, .github/test_files/tf/variables.tf, .github/test_files/tf/versions.tf, .github/workflows/tests.yaml, action.yaml
Currently, I added just the k8s manifest test just to verify if the approach is correct. We still need someone to add a `MONDOO_SECRET` to the repo though
Closes #16
=> ⭐️ Add workflow for testing the action

README.md, aws/README.md, docker-image/README.md, k8s-manifest/README.md, k8s/README.md, policy/README.md, terraform/README.md
=> Resolve minor markdown warnings

action.yaml
=> Add back our branding to the actions.yml file

action.yaml
The base level action exists only to populate the marketplace
=> Restore the old name + update description

.github/actions/spelling/README.md, .github/actions/spelling/advice.md, .github/test_files/k8s-manifest.yaml, .github/workflows/docker-image.yaml, .github/workflows/fmt-check.yaml, .github/workflows/k8s-manifest.yaml, .github/workflows/spell-check.yaml, .github/workflows/terraform.yaml, Makefile, README.md, action.yaml, aws/README.md, aws/action.yaml, docker-image/README.md, docker-image/action.yaml, k8s-manifest/README.md, k8s-manifest/action.yaml, k8s/README.md, k8s/action.yaml, policy/README.md, policy/action.yaml, setup/README.md, setup/action.yaml, terraform/README.md, terraform/action.yaml
format actions with prettier and run the fmt check in github actions pipeline
=> 🧹 format github action

.github/actions/spelling/expect.txt, README.md
=> Fix incorrect readme example

terraform-hcl/README.md, terraform-plan/README.md, terraform-state/README.md
=> 📄 Update terraform docs

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/workflows/spell-check.yaml
Update things to use the main mondoo dictionary
=> Update the spellcheck workflow with the org dictionary

README.md
Signed-off-by: Scott Ford <scott@scottford.io>
=> Updates links to community

README.md, github-repo/README.md, k8s-manifest/README.md, policy/README.md, terraform-hcl/README.md, terraform-plan/README.md, terraform-state/README.md
Make sure these match what's happening
=> Improve + add job names

.github/actions/spelling/line_forbidden.patterns, .github/dependabot.yml, .github/workflows/cla.yaml, .github/workflows/spell-check.yaml
=> Update spellcheck config + update actions with dependabot

.github/workflows/released.yaml
=> 📄 Automtaically update action version in READMEs on release

.github/workflows/released.yaml
Follow-up to https://github.com/mondoohq/actions/pull/45
=> 🧹 Remove unnecessary version patterns

.github/workflows/docker-image.yaml, .github/workflows/general-action.yaml, .github/workflows/github-repo.yaml, .github/workflows/k8s-manifest.yaml, action.yaml, aws/README.md, aws/action.yaml, docker-image/README.md, docker-image/action.yaml, github-org/README.md, github-org/action.yaml, github-repo/README.md, github-repo/action.yaml, k8s-manifest/README.md, k8s-manifest/action.yaml, k8s/README.md, k8s/action.yaml, policy/README.md, policy/action.yaml, terraform-hcl/README.md, terraform-hcl/action.yaml, terraform-plan/README.md, terraform-plan/action.yaml, terraform-state/README.md, terraform-state/action.yaml
=> 🐛 Add back `service-account-credentials`

.github/workflows/github-repo.yaml, github-org/action.yaml, github-repo/action.yaml
=> 🐛 Fix github repo and org actions

.github/workflows/terraform-plan.yaml, terraform-plan/README.md, terraform-plan/action.yaml
This PR updates the Terraform plan GH action by adding a new `input` for the `plan-file` to be scanned. It also updates docs and examples for the action. 
Signed-off-by: Scott Ford <scott@scottford.io>
=> Updates Terraform plan action

.github/workflows/docker-image.yaml, .github/workflows/k8s-manifest.yaml, github-org/README.md
This PR is to tidy our tests and ensure proper reporting.
=> Cleanup Workflows

README.md, aws/README.md, docker-image/README.md, github-org/README.md, github-repo/README.md, k8s-manifest/README.md, k8s/README.md, policy/README.md, terraform-hcl/README.md, terraform-plan/README.md, terraform-state/README.md
=> Fix dead docs links

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt, .github/actions/spelling/reject.txt
=> Update spellcheck config
